In [4]:
import tensorflow as tf

# Each value is called the element of the tensor
# x is the tensor object
x = tf.range( 12, dtype = tf.float32 )
x

tf.size(x)
x.shape

TensorShape([12])

In [12]:
# Tensor of size 'n' and shape (w,h) => h = w/n which is simple maths
# Init of a 2D matrix   
X = tf.reshape(x, (3,4))
X

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

In [19]:
# Init of a 3d Tensor with zeros
tf.zeros((2,3,4))
# Init of a 3d Tensor with ones
tf.ones((2,3,4))

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>